# Generated by Django 5.0.6 on 2025-09-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="생성 일자",
                        help_text="생성 일자",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="수정 일자", help_text="수정 일자", null=True
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, db_comment="이름", help_text="이름", null=True
                    ),
                ),
                (
                    "organization_number",
                    models.TextField(
                        blank=True, db_comment="기관 번호", help_text="기관 번호", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, db_comment="기관 주소", help_text="기관 주소", null=True
                    ),
                ),
                (
                    "telephone_number",
                    models.TextField(
                        blank=True, db_comment="기관 전화번호", help_text="기관 전화번호", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "기관",
                "db_table_comment": "기관",
                "ordering": ["id"],
            },
        ),
    ]
