# Generated by Django 5.0.6 on 2025-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="생성 일자", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 일자", null=True),
                ),
                ("patient_uuid", models.UUIDField(help_text="환자 uuid")),
                ("description", models.TextField(help_text="환자 설명")),
                (
                    "user_id",
                    models.BigIntegerField(blank=True, help_text="의사 아이디", null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, help_text="삭제 여부")),
            ],
            options={
                "verbose_name": "환자",
                "db_table_comment": "환자",
                "ordering": ["id"],
            },
        ),
    ]
