# Generated by Django 5.0.6 on 2025-10-16 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_uuid",
            field=models.UUIDField(
                default=uuid.UUID("aad24ff2-4f81-4638-aefc-635138a39f00"),
                editable=False,
                help_text="환자 uuid",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user_id",
            field=models.BigIntegerField(
                blank=True, default=1, help_text="의사 아이디", null=True
            ),
        ),
        migrations.CreateModel(
            name="OrganizationPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_number",
                    models.TextField(db_comment="차트 번호", help_text="차트 번호"),
                ),
                ("user_id", models.BigIntegerField(db_comment="의사", help_text="의사")),
                (
                    "organization",
                    models.ForeignKey(
                        db_comment="기관 ID",
                        help_text="기관",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_comment="환자 ID",
                        help_text="환자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "기관-환자",
                "db_table": "accounts_organizationpatient",
                "db_table_comment": "기관-환자 관계",
                "ordering": ["id"],
                "unique_together": {("organization", "patient")},
            },
        ),
    ]
